### ISSUE TITLE
Investigate alternatives for forum implementation

### ISSUE THREAD

**Issue by Zenidd** [Zenidd/bwm-forum#1]
Hey @JMbaena,

To get to the best possible solution you should investigate the different alternatives to deploy a forum.

Feel free to search on Chatgpt or any other searching tool.

**Comment by JMbaena** [comment]
Hello Juan Pablo, I've been looking into options to implement the Forobmw website, and I found these options:

InfinityFree (https://www.infinityfree.com/): This option is completely free and seems like a good choice as a personal development environment for a website without traffic.

Another option I found, which is paid, is  OVHCloud (https://www.ovhcloud.com/es-es/), but they are French 💩.

Without a doubt, the best option was IONOS, which offers a plan with 200GB of storage, a domain, and 9GB of RAM for 1 euro.

**Comment by JMbaena** [comment]
The test I did on InfinityFree.  http://rimos.freesite.online/ it’s a small test with a personal project I uploaded to see how it worked.
